#!python

import argparse
import sys

from aque.brokers import get_broker


parser = argparse.ArgumentParser()
parser.add_argument('-c', '--clear', action='store_true')
args = parser.parse_args()


broker = get_broker()
if args.clear:
    broker.clear()
broker.init()
